# Generated by Django 5.2.9 on 2025-12-31 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        ('sesiones', '0001_initial'),
        ('usuarios', '0002_alter_administrador_options_alter_jugador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_apostada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_realizadas', to='juegos.juego')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuestas_sesion', to='sesiones.sesion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='usuarios.jugador')),
            ],
            options={
                'verbose_name': 'Apuesta (Juega)',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='COMPLETADO', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, help_text='Ej: Tarjeta acabada en 1234', max_length=50, null=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_destino', to='usuarios.jugador', verbose_name='Jugador Destino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='usuarios.jugador', verbose_name='Jugador Origen')),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'ordering': ['-fecha'],
            },
        ),
    ]
