# Generated by Django 5.2.10 on 2026-01-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_fix_trigger'),
        ('sesiones', '0002_trigger_seguridad_sesion'),
        ('transacciones', '0002_add_triggers'),
        ('usuarios', '0003_alter_administrador_telefono_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apuesta',
            new_name='Juega',
        ),
        migrations.AlterModelOptions(
            name='juega',
            options={'ordering': ['-fecha'], 'verbose_name': 'Juega', 'verbose_name_plural': 'Juega'},
        ),
        migrations.AlterModelTable(
            name='juega',
            table='JUEGA',
        ),
    ]
