# Generated by Django 5.2.9 on 2025-12-31 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        ('usuarios', '0002_alter_administrador_options_alter_jugador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('Bono de Bienvenida', 'Bono de Bienvenida'), ('Tiradas Gratis', 'Tiradas Gratis'), ('Cashback', 'Cashback')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('condiciones', models.TextField(verbose_name='Condiciones/Requisitos')),
                ('beneficio', models.CharField(max_length=20)),
                ('max_jugadores', models.PositiveIntegerField(default=0, help_text='0 para ilimitado')),
                ('estado', models.BooleanField(default=False, help_text='Activo (True) / Inactivo (False)')),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('jugadores', models.ManyToManyField(related_name='promociones', through='eventos.Participa', to='usuarios.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='participa',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.promocion'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('aforo_maximo', models.PositiveIntegerField()),
                ('precio_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reglas', models.TextField(verbose_name='Reglas/Condiciones')),
                ('premio', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('abierto', 'Abierto'), ('en curso', 'En curso'), ('finalizado', 'Finalizado')], default='programado', max_length=20)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.juego')),
                ('participantes', models.ManyToManyField(related_name='torneos', through='eventos.Compite', to='usuarios.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='compite',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='participa',
            unique_together={('jugador', 'promocion')},
        ),
        migrations.AlterUniqueTogether(
            name='compite',
            unique_together={('jugador', 'torneo')},
        ),
    ]
