CREATE OR REPLACE TRIGGER TR_VALIDAR_APUESTAS
BEFORE INSERT OR UPDATE ON "JUEGOS_JUEGO"
FOR EACH ROW
BEGIN
    IF :NEW."APUESTA_MINIMA" > :NEW."APUESTA_MAXIMA" THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error: Minima mayor que maxima');
    END IF;
END;