# Generated by Django 5.2.9 on 2025-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('tragaperras', 'Tragaperras'), ('ruleta', 'Ruleta')], max_length=20)),
                ('apuesta_minima', models.FloatField()),
                ('apuesta_maxima', models.FloatField()),
                ('estado', models.BooleanField(default=True, help_text='Activo/Inactivo')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
