# Generated by Django 6.0 on 2026-01-04 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("tragaperras", "Tragaperras"), ("ruleta", "Ruleta")],
                        max_length=20,
                    ),
                ),
                (
                    "apuesta_minima",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                (
                    "apuesta_maxima",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(default=True, help_text="Activo/Inactivo"),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
    ]
