# Generated by Django 5.2.10 on 2026-01-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='tipo',
            field=models.CharField(choices=[('tragaperras', 'Tragaperras'), ('ruleta', 'Ruleta'), ('cartas', 'Cartas')], max_length=20),
        ),
    ]
