# Generated by Django 5.2.10 on 2026-01-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_fix_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AlterModelTable(
            name='juego',
            table='JUEGO',
        ),
    ]
