# Generated by Django 6.0 on 2026-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "dni",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellidos", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.IntegerField()),
                ("fecha_nacimiento", models.DateField()),
                ("contrasena", models.CharField(max_length=20)),
                ("baja", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
                "db_table": "ADMINISTRADOR",
            },
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "dni",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellidos", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("direccion", models.CharField(max_length=50)),
                ("telefono", models.IntegerField()),
                ("fecha_nacimiento", models.DateField()),
                ("contrasena", models.CharField(max_length=20)),
                ("cartera_monetaria", models.IntegerField()),
                ("baja", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Jugador",
                "verbose_name_plural": "Jugadores",
                "db_table": "JUGADOR",
            },
        ),
    ]
