# Generated by Django 5.2.10 on 2026-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_add_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='cartera_monetaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
