# Generated by Django 6.0 on 2026-01-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_actual", models.DateField(auto_now_add=True)),
                ("hora_inicio", models.TimeField(auto_now_add=True)),
                ("saldo_inicio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "regla1_limite_gasto_diario",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Límite de gasto diario establecido para esta sesión",
                        max_digits=10,
                    ),
                ),
                (
                    "regla2_limite_operaciones_hora",
                    models.IntegerField(
                        default=0, help_text="Límite de operaciones por hora"
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("duracion_sesion", models.DurationField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="DNI_JUGADOR",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="usuarios.jugador",
                    ),
                ),
            ],
            options={
                "db_table": "SESION",
                "ordering": ["-fecha_actual", "-hora_inicio"],
            },
        ),
    ]
