# Generated by Django 6.0 on 2026-01-11 17:45

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que esto apunte a tu última migración (ej: 0001_initial)
        ('sesiones', '0001_initial'), 
    ]

    operations = [
        migrations.RunSQL(
            # 1. SQL PARA CREAR EL DISPARADOR
            sql="""
            CREATE OR REPLACE TRIGGER TRG_PROTEGER_SESION_CERRADA
            BEFORE UPDATE ON SESION
            FOR EACH ROW
            BEGIN
                -- Si la sesión ya estaba cerrada (0) y se intenta hacer un UPDATE
                IF :OLD.activa = 0 THEN
                    RAISE_APPLICATION_ERROR(-20001, 'SEGURIDAD: No se pueden modificar datos de una sesión ya finalizada.');
                END IF;
            END;
            """,
            
            # 2. SQL PARA BORRARLO (Si deshacemos la migración)
            reverse_sql="DROP TRIGGER TRG_PROTEGER_SESION_CERRADA"
        )
    ]
